### ISSUE TITLE
Incorrect python version requirement

### ISSUE THREAD

**Issue by deepak-uk** [panoptes-organization/panoptes#121]
**Describe the bug**
Under installation process python requirement says >3.6 but actually it's 3.8

**Comment by deepak-uk** [comment]
Hi @fgypas,
Thank for your response.
I work with Argy and trying to learn more about git.
I was trying to install panoptes yesterday and was struggling with python version and today we found that it suppose to be 3.8. so after installing 3.8 it worked fine.
I have installed panoptes using conda and I am using linux mint.
Hope I will be able to contribute in this project, but first I need to understand

**Comment by fgypas** [comment]
Hi @deepak-uk 

Oh, ok, great. Well, welcome to the team then! Sure, take your time and feel free to open new issues or talk directly to @agardelakos 

Regarding the version, I think it works with 3.7 as well (at least on OSX).
So maybe we can in general add >=3.8 as a requirement to be consistent among all OS.

Best
Foivos

**Comment by fgypas** [comment]
One more thing I just realized. In the Dockerfile we use 3.6, so I think it should work as we use it for the tests. @agardelakos What do you think?

**Comment by fgypas** [comment]
Will update in #165
