### ISSUE TITLE
Full CRUD operation in DB

### ISSUE THREAD

**Issue by dafentoulis** [panoptes-organization/panoptes#128]
**Is your feature request related to a problem? Please describe.**
API only supports partial operations. Support for full CRUD operations should be implemented.

**Describe the solution you'd like**
Implement full CRUD operations using standard status codes and responses. 
I guess "CREATE" won't be exposed as this happens automatically, but it's good to have this operation for debugging reasons.

**Comment by fgypas** [comment]
Fixed in #129
