### ISSUE TITLE
Create custom logger in snakemake

### ISSUE THREAD

**Issue by fgypas** [panoptes-organization/panoptes#13]
Based on the idea introduced from Yohannes Koster we need to create a custom logger in snakemake.

We need to implement a custom logger, that sends updates to your server via HTTP/HTTPS. The user can invoke Snakemake with a special argument, say --wms-monitor, which would trigger the custom logger to be used in addition to console logging. This way, Snakemake could be started from the server process OR via the console, and in both cases, the server process would see the updates.

**Comment by fgypas** [comment]
We currently work on the following fork: https://bitbucket.org/fgypas/snakemake in the branch feature/wms-monitor

**Comment by fgypas** [comment]
- [ ] Make pull request to snakemake when we are confident for our changes

**Comment by fgypas** [comment]
blocked by #2

**Comment by agardelakos** [comment]
Also, we should consider the option to add in the snakemake PR, the option (cmd line argument?) to run not on a local instance of panoptes, but somewhere in the cloud. For that, we definitely need some sort of tokens/authorization. [issue 2](https://github.com/panoptes-organization/panoptes/issues/2)

**Comment by fgypas** [comment]
Fixed in https://github.com/snakemake/snakemake/pull/588
