### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by mhorlacher** [panoptes-organization/panoptes#155]
Considering that the last modification was >2 years ago, I was wondering whether development on this project is still active.

**Comment by fgypas** [comment]
Hi @mhorlacher 
We are not in active development, but the project/server is still working. I use it in a daily basis to track workflows.
In case you find any issues we are happy to fix them.
Best
Foivos

**Comment by fgypas** [comment]
@mhorlacher  I started making some changes in the package. I close the ticket and please open other tickets if you run into any issues.
