### ISSUE TITLE
Deploy panoptes for production

### ISSUE THREAD

**Issue by fgvieira** [panoptes-organization/panoptes#172]
**Is your feature request related to a problem? Please describe.**
I need a way to monitor running `snakemake` pipelines in a production environment, and decided to try `panoptes`.
From the singularity image, it was super easy to get it to work!

However, a warning message comes up that:
```
WARNING: This is a development server. Do not use it in production deployment. Use a production WSGI server instead.
```
I looked a bit around but could only find a generic `flask` [tutorial](https://flask.palletsprojects.com/en/2.2.x/tutorial/deploy/), but it is not clear how that applies to `panoptes` (e.g. how do you define the `SECRET_KEY`?). 

Is there any documentation on how to deploy `panoptes` for production.
How would you recommend to do it?

**Comment by fgvieira** [comment]
Not sure if it the best way to do it, but I managed to do it with `waitress`.

1. Follow instruction in https://github.com/panoptes-organization/panoptes#install-from-conda-and-run-server
2. Instead of run the server with `panoptes`, run `waitress-serve --port 5000 "panoptes.app:app"`

@fgypas I'll leave it open, since it would still be nice to have an "official" way to do it. :smile:

**Comment by fgypas** [comment]
Thanks a lot @fgvieira 
That's a good solution to add WSGI server and feel free to open a PR.
