### ISSUE TITLE
Add CI/CD support

### ISSUE THREAD

**Issue by fgypas** [panoptes-organization/panoptes#29]
Automate the build and test of the service using CI/CD

- [x] CI
- [x] CI-docker build
- [ ] CD

**Comment by fgypas** [comment]
@agardelakos How far are we on this one? Should we close this or move it to another project? E.g. https://github.com/panoptes-organization/panoptes/projects/4

**Comment by agardelakos** [comment]
@fgypas we can close as implemented this ticket. The tracking for CD functionality shall be done in #62
