### ISSUE TITLE
UI bug: Main page - workflows now running gets stuck at 1

### ISSUE THREAD

**Issue by agardelakos** [panoptes-organization/panoptes#42]
when a local run (from snakemake-example-workflow) is performed and the results folder is already present, the badge "workflows now running" in panoptes main page always shows 1 and the badge "workflows executed" never gets populated.

Expected behaviour: even in that corner case, the main page should populate the badges correctly.

**Comment by fgypas** [comment]
relates to #51

**Comment by fgypas** [comment]
I think this is fixed in 2b5125a9d196e6afef9bf561e5c116135b6b435c

**Comment by fgypas** [comment]
I am re-opening. The issue is still there.

**Comment by fgypas** [comment]
The log that is passed in such cases is:

`{'msg': "{'level': 'info', 'msg': 'Nothing to be done.', 'indent': False}", 'timestamp': 'Wed Feb  5 20:17:49 2020', 'id': 6}`
