### ISSUE TITLE
Create conda package

### ISSUE THREAD

**Issue by fgypas** [panoptes-organization/panoptes#46]
- [x] Add conda instructions and package it for bioconda

- [x] Add pypi package

**Comment by fgypas** [comment]
I registered the following conda organization in anaconda.org:
https://anaconda.org/panoptes-organization/dashboard

**Comment by fgypas** [comment]
Waiting for https://github.com/snakemake/snakemake/pull/588

**Comment by agardelakos** [comment]
pypi package can be found here: https://pypi.org/project/panoptes-ui/

**Comment by agardelakos** [comment]
conda package can be found here: https://anaconda.org/panoptes-organization/panoptes-ui
