### ISSUE TITLE
Separate front-end from back-end

### ISSUE THREAD

**Issue by fgypas** [panoptes-organization/panoptes#5]
At the moment it's fine the way we use bootstrap/coreui.io with jinja in flask, but before the project grows too much, we have to think of splitting the front-end from the back-end. We could use coreui.io with React, Angular or Vue.js. The front end server can be node.js.

**Comment by fgypas** [comment]
relates to #27

**Comment by fgypas** [comment]
relates also to #53

**Comment by kinow** [comment]
Good idea. Apache Airflow has both mixed too. I think Galaxy started like that, not sure if changed. We are building our workflow system (Cylc) with separate backend and frontend, which helps a lot to avoid code contamination, and keep the separation of concerns.

**Comment by fgypas** [comment]
Closing for now
