### ISSUE TITLE
Add project documentation

### ISSUE THREAD

**Issue by kinow** [panoptes-organization/panoptes#59]
Hi,

Learned about Panoptes recently, very interesting project!

I'm working on an interface for a workflow scheduler/manager. I'm watching the project for releases, and will check again its status after the initial work with snakemake workflow has been done/released.

I couldn't find a ticket for the documentation, not sure if that's too early for that? But what I am more interested is in learning how you guys are planning to get other workflow systems to work with Panoptes.

The sooner that is defined, the easier it would be for developers involved in these projects to assess how hard it would be to create the integration for Panoptes :)

Cheers
Bruno

**Comment by fgypas** [comment]
Hi @kinow 

Thank you for your interest in panoptes.

> I couldn't find a ticket for the documentation, not sure if that's too early for that?

So what you would like to have is an abstraction of how to support a different workflow engine?

> But what I am more interested is in learning how you guys are planning to get other workflow systems to work with Panoptes.

The plan is that after snakemake we can support other engines (e.g. toil that support CWL pipelines see #32 ). The logic should be similar to the one from snakemake where we send Http requests from snakemake to panoptes. What happens is that snakemake requests an id from the server and then every post request to the server is using this id to refer to the current workflow. Something similar could happen for a different engine. The only problem at the moment is that we rely on custom logs and this means that you have to think in advance what information you want to store in the database and whatnot (this is different regarding the workflow engine). Of course, if someone is interested in adding support for any other workflow engine is more than welcome to start doing it now. We can discuss this if you want to work on it.

Let me know whether this answers your questions or it raised more

Best
Foivos

**Comment by kinow** [comment]
Hi Foivos,

That's the main part of the documentation I was after, thanks. I will probably keep lurking/watching the repo, waiting for the code to stabilize more before giving it a try.

Will also keep an eye on your UI, as at least until October next year I will keep working on a similar UI, so may have some overlap where I can either learn something useful, or contribute here :+1: 

Feel free to close the issue if you prefer to have smaller issues or to keep track of documentation somewhere else.

Cheers
Bruno
