### ISSUE TITLE
Table refactor

### ISSUE THREAD

**Issue by fgypas** [panoptes-organization/panoptes#95]
**Is your feature request related to a problem? Please describe.**
The workflows page show always the newest pipeline/workflow at the end

**Describe the solution you'd like**
Add an option to sort the pipelines with a different order (e.g. based on the date).

**Comment by dafentoulis** [comment]
What dynamically means in this case?
Will sort buttons next to column names do the job?

**Comment by fgypas** [comment]
Sorry, it's a bad description. What I mean is to have a way to sort the workflow table based on specific columns. Something like the following:
https://www.cssscript.com/demo/minimal-table-sorting-library-sortable-js/.
This would allow us to sort the table (e.g. by date). Does that make sense?

**Comment by dafentoulis** [comment]
No problem! Since we use bootstrap, we can use its sorting and pagination which looks like this:
https://mdbootstrap.com/docs/jquery/tables/sort

**Comment by fgypas** [comment]
Yes, I agree. It looks great!

**Comment by dafentoulis** [comment]
I'd suggest we merge this with 94 and change the title to "table refactor" or similar as I can add pagination, sorting and edit/delete buttons in one merge.

Buttons can appear in a new column called "Actions" or similar.
* Edit: I don't see anything else being editable other than the name.
* Delete: can make an ajax call to the api and if the workflow is succesfully deleted from the db, then it is also deleted from the table

Sorting is added on all columns, we can change that easily.
Pagination is added, client-side. Later this can be done server-side if needed. Default selections are 10,25,50,100.

What do you think?

**Comment by fgypas** [comment]
Yes, I agree with the suggestion. I closed #94 and changed the current title to "Table refactor".

**Comment by fgypas** [comment]
Fixed in #134
